from __future__ import annotations

import json
from pathlib import Path

from pipeline.agentic.workflow_doctor import inspect_carousel_package


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def issue_codes(report) -> set[str]:
    return {issue.code for issue in report.issues}


def test_flags_raw_scene_rejected_but_generation_allowed(tmp_path: Path) -> None:
    package = tmp_path / "one-brain-cell-at-home"
    package.mkdir()
    (package / "raw-scene-row.md").write_text(
        "STATUS: REJECTED\nGeneration must stop until creator-approved storyboard exists.\n",
        encoding="utf-8",
    )
    write_json(package / "visual-plan-quality.json", {"status": "PASS", "can_generate": True})

    report = inspect_carousel_package(package)

    assert "raw_scene_rejected_but_generation_allowed" in issue_codes(report)
    assert report.highest_severity == "blocker"


def test_flags_handoff_blocker_with_fake_publishable_final_state(tmp_path: Path) -> None:
    package = tmp_path / "handoff-with-fake-final"
    package.mkdir()
    write_json(package / "image-generation.json", {"status": "handoff_ready"})
    write_json(package / "final-images.json", {"status": "generated", "done": True, "publishable": True})
    (package / "image-generation-blocker.md").write_text(
        "No final PNGs were generated by this CLI run.\n",
        encoding="utf-8",
    )

    report = inspect_carousel_package(package)

    assert "stale_blocker_with_generated_finals" in issue_codes(report)
    assert report.highest_severity == "blocker"


def test_flags_missing_required_c_layer_artifacts_for_fresh_generation(tmp_path: Path) -> None:
    package = tmp_path / "private-captions-fresh-a-story"
    package.mkdir()
    write_json(package / "manifest.json", {"status": "fresh_generation_in_progress"})
    write_json(package / "slides.json", {"slides": [{"slide": 1, "copy": "dumber"}]})
    write_json(package / "visual-plan-quality.json", {"status": "GO"})
    (package / "final-clean").mkdir()

    report = inspect_carousel_package(package)

    codes = issue_codes(report)
    assert "missing_prompt_pack" in codes
    assert "missing_visual_debate" in codes
    assert "missing_post_copy_visual_room" in codes
    assert "missing_final_audit" in codes
    assert report.highest_severity == "blocker"


def test_clean_handoff_package_reports_actionable_non_publishable_state(tmp_path: Path) -> None:
    package = tmp_path / "i-have-no-car-i-ll-walk"
    package.mkdir()
    write_json(package / "manifest.json", {"status": "READY_FOR_CODEX_BUILTIN_GENERATION"})
    write_json(package / "prompt-pack.json", {"slides": [{"slide": 1, "prompt": "scene"}]})
    write_json(package / "visual-debate.json", {"decision": "GO"})
    write_json(package / "post-copy-visual-room.json", {"decision": "GO"})
    write_json(package / "visual-plan-quality.json", {"status": "PASS", "can_generate": True})
    write_json(package / "image-generation.json", {"status": "handoff_ready"})
    write_json(package / "final-images.json", {"status": "handoff_ready", "done": False, "publishable": False})

    report = inspect_carousel_package(package)

    assert report.highest_severity == "warning"
    assert "handoff_ready_not_publishable" in issue_codes(report)
    assert "missing_prompt_pack" not in issue_codes(report)


def test_flags_publishable_claim_without_visual_qa(tmp_path: Path) -> None:
    package = tmp_path / "fake-publishable"
    package.mkdir()
    write_json(package / "final-images.json", {"status": "generated", "done": True, "publishable": True})
    write_json(package / "final-audit.json", {"status": "PASS", "pass": True})
    (package / "final").mkdir()
    (package / "final-reels-stories").mkdir()

    report = inspect_carousel_package(package)

    assert "publishable_without_visual_qa" in issue_codes(report)
    assert report.highest_severity == "blocker"


def test_flags_missing_reels_stories_when_instagram_finals_exist(tmp_path: Path) -> None:
    package = tmp_path / "partial-native-final"
    package.mkdir()
    (package / "final").mkdir()
    (package / "final" / "slide-01.png").write_bytes(b"not a real png")
    write_json(package / "final-images.json", {"status": "generated", "done": True, "publishable": False})

    report = inspect_carousel_package(package)

    assert "missing_reels_stories_final_folder" in issue_codes(report)
    assert report.highest_severity == "blocker"
