from __future__ import annotations

import json
from pathlib import Path

from pipeline.agentic.workflow_doctor import inspect_carousel_package


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def issue_codes(report) -> set[str]:
    return {issue.code for issue in report.issues}


def test_flags_raw_scene_rejected_but_generation_allowed(tmp_path: Path) -> None:
    package = tmp_path / "one-brain-cell-at-home"
    package.mkdir()
    (package / "raw-scene-row.md").write_text(
        "STATUS: REJECTED\nGeneration must stop until creator-approved storyboard exists.\n",
        encoding="utf-8",
    )
    write_json(package / "visual-plan-quality.json", {"status": "PASS", "can_generate": True})

    report = inspect_carousel_package(package)

    assert "raw_scene_rejected_but_generation_allowed" in issue_codes(report)
    assert report.highest_severity == "blocker"


def test_flags_handoff_blocker_with_fake_publishable_final_state(tmp_path: Path) -> None:
    package = tmp_path / "handoff-with-fake-final"
    package.mkdir()
    write_json(package / "image-generation.json", {"status": "handoff_ready"})
    write_json(package / "final-images.json", {"status": "generated", "done": True, "publishable": True})
    (package / "image-generation-blocker.md").write_text(
        "No final PNGs were generated by this CLI run.\n",
        encoding="utf-8",
    )

    report = inspect_carousel_package(package)

    assert "stale_blocker_with_generated_finals" in issue_codes(report)
    assert report.highest_severity == "blocker"


def test_flags_blocked_generation_manifest(tmp_path: Path) -> None:
    package = tmp_path / "blocked-generation"
    package.mkdir()
    write_json(package / "image-generation.json", {"status": "blocked", "reason": "dimension gate failed"})
    write_json(package / "final-images.json", {"status": "blocked", "publishable": False})
    (package / "image-generation-blocker.md").write_text("status: BLOCKED\n", encoding="utf-8")

    report = inspect_carousel_package(package)

    assert "image_generation_blocked" in issue_codes(report)
    assert report.highest_severity == "blocker"


def test_flags_semantic_generation_blockers_from_current_package_shape(tmp_path: Path) -> None:
    package = tmp_path / "rules-of-marriage-unofficial-edition"
    package.mkdir()
    write_json(
        package / "final-images.json",
        {
            "status": "not_final",
            "final_status": "blocked_for_native_1080x1440_and_exact_text_qa",
            "publishable": False,
        },
    )
    write_json(
        package / "text-generated-candidates.json",
        {
            "publish_gate": {"status": "BLOCKED"},
            "textless_sources": {"status": "REJECTED_HARD_FAIL"},
        },
    )

    report = inspect_carousel_package(package)

    codes = issue_codes(report)
    assert "semantic_generation_blocked" in codes
    assert "publish_gate_blocked" in codes
    assert "textless_sources_rejected" in codes
    assert report.blocked is True
    assert report.highest_severity == "blocker"


def test_flags_active_textless_prompt_artifact(tmp_path: Path) -> None:
    package = tmp_path / "rules-of-marriage-unofficial-edition"
    package.mkdir()
    write_json(
        package / "prompt-pack.json",
        {
            "slides": [
                {
                    "slide": 4,
                    "text": "Rule no. 3\nAlways ask if the fight is still happening.",
                }
            ]
        },
    )
    prompt_dir = package / "codex-image-prompts"
    prompt_dir.mkdir()
    (prompt_dir / "square-proof-slide-04.prompt.txt").write_text(
        "\n".join(
            [
                "PALETTE: warm ivory paper.",
                "HARD FAIL: yellow, sepia, parchment.",
                "Style lock: Observational Intimacy Premium.",
                "ON-IMAGE TEXT: exact final copy.",
                "Each identity reference image must be attached to the call.",
                "Preserve Aachu and Zuv face identity.",
                "Brandmark: tiny handwritten @a.storyof.two in top-right.",
                "No split-screen divider may appear in final art.",
                "This is source art for a proof; leave clean upper-middle paper space for exact text placement afterward.",
                "Text rule for source art:",
                "Do not include any text, lettering, brandmark, labels, signs, readable packaging words, random letters, watermarks, speech bubbles, or UI in this source image.",
            ]
        ),
        encoding="utf-8",
    )

    report = inspect_carousel_package(package)

    assert "active_textless_prompt" in issue_codes(report)
    assert report.blocked is True
    assert report.highest_severity == "blocker"


def test_flags_missing_required_c_layer_artifacts_for_fresh_generation(tmp_path: Path) -> None:
    package = tmp_path / "private-captions-fresh-a-story"
    package.mkdir()
    write_json(package / "manifest.json", {"status": "fresh_generation_in_progress"})
    write_json(package / "slides.json", {"slides": [{"slide": 1, "copy": "dumber"}]})
    write_json(package / "visual-plan-quality.json", {"status": "GO"})
    (package / "final-clean").mkdir()

    report = inspect_carousel_package(package)

    codes = issue_codes(report)
    assert "missing_prompt_pack" in codes
    assert "missing_visual_debate" in codes
    assert "missing_post_copy_visual_room" in codes
    assert "missing_final_audit" in codes
    assert report.highest_severity == "blocker"


def test_clean_handoff_package_reports_actionable_non_publishable_state(tmp_path: Path) -> None:
    package = tmp_path / "i-have-no-car-i-ll-walk"
    package.mkdir()
    write_json(package / "manifest.json", {"status": "READY_FOR_CODEX_BUILTIN_GENERATION"})
    write_json(package / "prompt-pack.json", {"slides": [{"slide": 1, "prompt": "scene"}]})
    write_json(package / "visual-debate.json", {"decision": "GO"})
    write_json(package / "post-copy-visual-room.json", {"decision": "GO"})
    write_json(package / "visual-plan-quality.json", {"status": "PASS", "can_generate": True})
    write_json(package / "image-generation.json", {"status": "handoff_ready"})
    write_json(package / "final-images.json", {"status": "handoff_ready", "done": False, "publishable": False})

    report = inspect_carousel_package(package)

    assert report.highest_severity == "warning"
    assert "handoff_ready_not_publishable" in issue_codes(report)
    assert "missing_prompt_pack" not in issue_codes(report)


def test_flags_publishable_claim_without_visual_qa(tmp_path: Path) -> None:
    package = tmp_path / "fake-publishable"
    package.mkdir()
    write_json(package / "final-images.json", {"status": "generated", "done": True, "publishable": True})
    write_json(package / "final-audit.json", {"status": "PASS", "pass": True})
    (package / "final").mkdir()
    (package / "final-reels-stories").mkdir()

    report = inspect_carousel_package(package)

    assert "publishable_without_visual_qa" in issue_codes(report)
    assert report.highest_severity == "blocker"


def test_flags_missing_reels_stories_when_instagram_finals_exist(tmp_path: Path) -> None:
    package = tmp_path / "partial-native-final"
    package.mkdir()
    (package / "final").mkdir()
    (package / "final" / "slide-01.png").write_bytes(b"not a real png")
    write_json(package / "final-images.json", {"status": "generated", "done": True, "publishable": False})

    report = inspect_carousel_package(package)

    assert "missing_reels_stories_final_folder" in issue_codes(report)
    assert report.highest_severity == "blocker"
